### ISSUE TITLE
Updating the email library to support tls 1.2

### ISSUE THREAD

**Issue by vhodosov** [aquality-automation/aquality-tracking-api#101]
Currently, the reporting portal does not support tls 1.2. Aws is transferring its entire API from September 15 to tls 1.2, and from September 15 to December 31, it will disable support for tls 1.0 and 1.1.
For now reporting portal use library that does not support tls 1.2

      <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <version>1.4.7</version>
        </dependency>

**Comment by aqualityAutomation** [comment]
https://github.com/aquality-automation/aquality-tracking-api/pull/102
